[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sulfurvision"
version = "0.0.0"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.0"
dependencies = [
    "Pillow",
    "numpy",
    "pyopencl"
]
